-- Seed gerado a partir de equipe_ativa.xlsx (nome, e-mail, categoria)
insert into consultores (nome, email, categoria) values
  ('Adriano Márcio Macedo Campos', 'adriano.campos@aquila.com.br', 'Classe B - 2'),
  ('Afonso Celso Corrêa de Araújo Valle', 'afonso.valle@aquila.com.br', 'Classe B - 2'),
  ('Alefy de Souza Pimentel', 'alefy.pimentel@aquila.com.br', 'Estagiário'),
  ('Alexaenny Ketelly de Melo Alves', 'alexaenny.alves@aquila.com.br', 'Trainee 1'),
  ('Alexandre Coelho Vinhal', 'alexandre.vinhal.fpj@aquila.com.br', 'Fornecedor'),
  ('Alice Thereza Faria Costa Senna', 'alice.senna.fpj@aquila.com.br', 'Fornecedor'),
  ('Aline Moreira Martins', 'aline.martins@aquila.com.br', 'Cientista de Dados Pleno 2'),
  ('Aline Pontes Hübner', 'aline.hubner@aquila.com.br', 'Pleno 2'),
  ('Allan Carlos de Oliveira Carvalho', 'allan.carvalho@aquila.com.br', 'Classe D - 3'),
  ('Allyson Pimenta Freire', 'allyson.freire@aquila.com.br', 'Classe C - 1'),
  ('Alvacir Pedroso Júnior', 'alvacir.pedroso@aquila.com.br', 'Classe B - 1'),
  ('Amanda Cristina Marinho Trindade', 'amanda.marinho@aquila.com.br', 'Pleno 2'),
  ('Ana Elisa Lima dos Santos', 'anaelisa.santos@aquila.com.br', 'Classe B - 1'),
  ('Ana Julia Freitas Santos', 'anajulia.santos@aquila.com.br', 'Trainee 1'),
  ('Ana Luisa Casagrande Hannickel', 'analuisa.hannickel@aquila.com.br', 'Trainee 1'),
  ('Ana Luiza Dos Santos Jacob', 'analuiza.jacob@aquila.com.br', 'Não se aplica'),
  ('Ana Luiza Kan Ning Lima I', 'analuiza.lima@aquila.com.br', 'Classe E - 3'),
  ('Ana María Escobar Botero', 'anamaria.escobar@aquilapacifico.com', 'Asociado 2'),
  ('Anderson Samuel Gonçalves da Silva', 'anderson.goncalves@aquila.com.br', 'Classe E - 3'),
  ('André de Alencar Rangel', 'andre.rangel@aquila.com.br', 'Classe C - 3'),
  ('André Felipe Duarte Gonçalves', 'andre.duarte@aquila.com.br', 'Classe D - 1'),
  ('Andréa Muniz do Nascimento', 'andrea.nascimento@aquila.com.br', 'Consultor Pedagógico'),
  ('Anna Luiza Simões Santos Paganucci', 'anna.simoes@aquila.com.br', 'Classe D - 3'),
  ('Antônio Marcos Melo Albuquerque', 'antonio.albuquerque.fpj@aquila.com.br', 'Fornecedor'),
  ('Aquiles Oliveira Mendes da Silva', 'aquiles.silva@aquila.com.br', 'Classe D - 3'),
  ('Ariel Brito da Costa', 'ariel.costa@aquila.com.br', 'Classe D - 1'),
  ('Ariel Morais Junior', 'ariel.junior@aquila.com.br', 'Auxiliar Técnico'),
  ('Arthur Gonçalves da Silva', 'arthur.silva@aquila.com.br', 'Classe E - 3'),
  ('Arthur Jansen Oliveira', 'arthur.oliveira@aquila.com.br', 'Desenvolvedor Pleno 1'),
  ('Aryanne Beatriz Alves da Luz', 'aryanne.luz@aquila.com.br', 'Estagiário'),
  ('Ashley Vitoria Gregorio de Jesus Pereira', 'ashley.pereira@aquila.com.br', 'Estagiário'),
  ('Augusto Pereira Leite Massa', 'augusto.massa@aquila.com.br', 'Classe B - 2'),
  ('Bárbara Godoy Morais', 'barbara.morais@aquila.com.br', 'Classe C - 1'),
  ('Beatriz Bianco Gamba', 'beatriz.gamba@aquila.com.br', 'Classe D - 2'),
  ('Bernardo Grisolino Coelho', 'bernardo.grisolino@aquila.com.br', 'Classe D - 1'),
  ('Bethânia Maria Rodrigues Alves', 'bethania.alves@aquila.com.br', 'Classe C - 3'),
  ('Brenda Lemes Borges', 'brenda.borges@aquila.com.br', 'Trainee 2'),
  ('Brenda Santos de Miranda', 'brenda.miranda@aquila.com.br', 'Trainee 2'),
  ('Brenda Victoria Pertile', 'brenda.pertile@aquila.com.br', 'Estagiário'),
  ('Breno Onofre Ferreira Rocha', 'breno.ferreira@aquila.com.br', 'Classe D - 1'),
  ('Bruna Ferreira Mello Reis', 'bruna.ferreira@aquila.com.br', 'Classe D - 1'),
  ('Bruna Vitória Alencar Peixoto Bem', 'bruna.peixoto@aquila.com.br', 'Júnior 2'),
  ('Bruno Franco Beraldi Coelho', 'bruno.beraldi@aquila.com.br', 'Classe C - 1'),
  ('Bruno Gomes Marques Aguilar', 'bruno.aguilar@aquila.com.br', 'Classe B - 1'),
  ('Bruno Maurici Passarella', 'bruno.passarella@aquila.com.br', 'Auxiliar em Gestão 2'),
  ('Bruno Starling Simão', 'bruno.starling@aquila.com.br', 'Classe C - 3'),
  ('Cainã Araújo Pavani', 'caina.pavani@aquila.com.br', 'Trainee 3'),
  ('Caique Almeida Caires', 'caique.caires@aquila.com.br', 'Classe E - 3'),
  ('Camila Calijorne Rolim', 'camila.rolim@aquila.com.br', 'Trainee 1'),
  ('Camilla Andrade Naime', 'camilla.naime@aquila.com.br', 'Não se aplica'),
  ('Carla do Espírito Santo Pereira', 'carla.pereira@aquilaiberia.com', 'Trainee 2'),
  ('Carlos Alberto Bottrel Coutinho', 'carlos.bottrel@aquila.com.br', 'Não se aplica'),
  ('Carlos Eduardo Silva Rizzetto', 'carlos.rizzetto.fpj@aquila.com.br', 'Fornecedor'),
  ('Carolina Correia Garcia', 'carolina.garcia@aquila.com.br', 'Classe D - 2'),
  ('Carolina Marques Mendes', 'carolina.mendes@aquila.com.br', 'Classe B - 1'),
  ('Catarina Albuquerque da Costa Roque', 'catarina.roque@aquila.com.br', 'Classe D - 2'),
  ('Cecília Andrade Azevedo', 'cecilia.azevedo@aquila.com.br', 'Classe E - 3'),
  ('Celso Junior Leite Batista', 'celso.batista@aquila.com.br', 'Classe C - 1'),
  ('Celso Rodrigues do Prado Neto', 'celso.prado@aquila.com.br', 'Classe C - 1'),
  ('Christhian Smith Gomez Hernandez', 'christhian.gomez@aquilapacifico.com', 'Júnior 1'),
  ('Christian Daniel Terrazas Matias', 'christian.matias@aquila.com.br', 'Estagiário'),
  ('Cintia Menegardo Corona', 'cintia.corona@aquila.com.br', 'Classe E - 3'),
  ('Cláudia Bessas Juscelino', 'claudia.bessas@aquilaiberia.com', 'Classe B - 2'),
  ('Cláudia Mara Souza Stocco', 'claudia.stocco@aquila.com.br', 'Não se aplica'),
  ('Cláudia Melo Silva de Almeida Terra', 'claudia.almeida.fpj@aquila.com.br', 'Fornecedor'),
  ('Daniela Avellar Belezia', 'daniela.belezia@aquila.com.br', 'Trainee 1'),
  ('Danilo Bramante Batista', 'danilo.batista@aquila.com.br', 'Auxiliar em Gestão 2'),
  ('Danilo Soares de Lima', 'danilo.lima@aquila.com.br', 'Classe C - 3'),
  ('Danilo Wanderley Lapa', 'danilo.lapa@aquila.com.br', 'Cientista de Dados Júnior 2'),
  ('Davi Barros Pereira', 'davi.barros@aquila.com.br', 'Classe B - 1'),
  ('David Michael Pereira dos Anjos', 'david.pereira@aquila.com.br', 'Classe E - 3'),
  ('Dayanne dos Santos Vieira', 'dayanne.vieira@aquila.com.br', 'Classe C - 3'),
  ('Denilson David Damalgo', 'denilson.damalgo@aquila.com.br', 'Classe D - 3'),
  ('Dhandara Oliveira Queiroz', 'dhandara.queiroz@aquila.com.br', 'Classe D - 2'),
  ('Diego Henrique Gonçalves Santos', 'diego.santos@aquila.com.br', 'Não se aplica'),
  ('Diego Magno de Oliveira', 'diego.oliveira@aquila.com.br', 'Classe C - 2'),
  ('Diego Vaz Teixeira de Souza', 'diego.souza@aquila.com.br', 'Trainee 1'),
  ('Douglas Américo da Silva', 'douglas.americo@aquila.com.br', 'Classe D - 1'),
  ('Douglas Ferreira Lourenço', 'douglas.lourenco@aquila.com.br', 'Classe C - 2'),
  ('Eduardo Cintra Felipe de Oliveira', 'eduardo.oliveira@aquila.com.br', 'Estagiário'),
  ('Eduardo de Amorim', 'eduardo.amorim@aquila.com.br', 'Fornecedor'),
  ('Eduardo Queiroz de Almeida Medrado', 'eduardo.medrado@aquila.com.br', 'Trainee 1'),
  ('Eliel Joabe de Souza', 'eliel.souza@aquila.com.br', 'Classe C - 1'),
  ('Eliezer Bueno de Melo', 'eliezer.bueno@aquila.com.br', 'Classe C - 1'),
  ('Emily Guimarães Pereira', 'emily.pereira@aquila.com.br', 'Estagiário'),
  ('Ericka Sanny Batista Oliveira', 'ericka.oliveira@aquila.com.br', 'Não se aplica'),
  ('Erico Costa Barros', 'erico.barros@aquila.com.br', 'Classe A'),
  ('Ernaldo Cavalcante Soares dos Santos', 'ernaldo.cavalcante@aquila.com.br', 'Classe D - 2'),
  ('Esther Alves Gomes', 'esther.gomes@aquila.com.br', 'Estagiário'),
  ('Euller de Sá Barros', 'euller.barros@aquila.com.br', 'Classe D - 1'),
  ('Evandro Ribeiro Gomes de Assis', 'evandro.ribeiro@aquila.com.br', 'Classe E - 3'),
  ('Everaldo Pimentel Barbosa', 'everaldo.barbosa@aquila.com.br', 'Auxiliar Técnico'),
  ('Fabiana de Brito', 'fabiana.brito@aquila.com.br', 'Classe E - 3'),
  ('Fabiana de Campos Fiorucci', 'fabiana.fiorucci@aquila.com.br', 'Trainee 1'),
  ('Fabio Matheus Virginio Da Silva', 'fabio.silva@aquila.com.br', 'Estagiário'),
  ('Fábio Vítor Chaves Braga', 'fabio.braga@aquila.com.br', 'Classe E - 2'),
  ('Fabrício Machado Righetti', 'fabricio.righetti@aquila.com.br', 'Classe B - 2'),
  ('Fagner Luiz Vieira', 'fagner.vieira@aquila.com.br', 'Classe D - 1'),
  ('Felipe Augusto de Mello Freire', 'felipe.freire@aquila.com.br', 'Classe C - 1'),
  ('Felipe Maia Dalcin', 'felipe.dalcin@aquila.com.br', 'Classe C - 3'),
  ('Felipe Pires de Oliveira', 'felipe.pires@aquila.com.br', 'Classe B - 2'),
  ('Felipe Siqueira Leôncio', 'felipe.leoncio@aquila.com.br', 'Trainee 1'),
  ('Fernanda Céli De Almeida Marçal', 'fernanda.marcal@aquila.com.br', 'Classe D - 2'),
  ('Fernanda Cristina Gonzaga', 'fernanda.gonzaga@aquila.com.br', 'Não se aplica'),
  ('Fernanda de Faria Abreu Ferracioli', 'fernanda.abreu@aquila.com.br', 'Não se aplica'),
  ('Fernanda Fernandes Bezerra', 'fernanda.fernandes.fpj@aquila.com.br', 'Fornecedor'),
  ('Fernanda Pontes Santana', 'fernanda.santana.fpj@aquila.com.br', 'Fornecedor'),
  ('Fernanda Soarez Diniz', 'fernanda.diniz@aquila.com.br', 'Analista Sistemas UX Júnior 1'),
  ('Fernando Moura Mattos', 'fernando.moura@aquila.com.br', 'Classe B - 2'),
  ('Fernando Willian Santos', 'fernando.willian@aquila.com.br', 'Classe E - 3'),
  ('Flavia Mendes Rocha', 'flavia.rocha@aquila.com.br', 'Não se aplica'),
  ('Flávio Pereira Maciel Grimberg', 'flavio.grimberg@aquila.com.br', 'Classe B - 1'),
  ('Gabriel Barbi Teixeira', 'gabriel.teixeira@aquila.com.br', 'Trainee 1'),
  ('Gabriel Borges Leal da Silva', 'gabriel.silva@aquila.com.br', 'Classe E - 3'),
  ('Gabriel de Quadros Seratto', 'gabriel.seratto@aquila.com.br', 'Classe C - 1'),
  ('Gabriel Francisco Amaral Esteves', 'gabriel.esteves@aquila.com.br', 'Estagiário'),
  ('Gabriela Silva da Silva', 'gabriela.silva@aquila.com.br', 'Trainee 2'),
  ('Gilmar Lacerda Merlo', 'gilmar.merlo@aquila.com.br', 'Classe D - 1'),
  ('Gilson Andrade Coelho', 'gilson.coelho@aquila.com.br', 'Sênior 1'),
  ('Glaucio Igor de Lima', 'glaucio.lima@aquila.com.br', 'Classe D - 3'),
  ('Guilherme Araújo Pimentel', 'guilherme.araujo@aquila.com.br', 'Classe D - 1'),
  ('Guilherme Carvalho de Albuquerque', 'guilherme.albuquerque@aquila.com.br', 'Classe E - 3'),
  ('Guilherme de Souza Nascimento', 'guilherme.nascimento@aquila.com.br', 'Trainee 1'),
  ('Guilherme Scharbel Moreira Da Costa', 'guilherme.moreira@aquila.com.br', 'Trainee 1'),
  ('Guilherme Souza Ribas', 'guilherme.ribas@aquila.com.br', 'Classe B - 2'),
  ('Gustavo Ferreira Licio', 'gustavo.licio@aquila.com.br', 'Estagiário'),
  ('Gustavo Miranda Caran', 'gustavo.caran@aquila.com.br', 'Cientista de Dados Pleno 3'),
  ('Gustavo Rossi Carbajo', 'gustavo.carbajo@aquila.com.br', 'Classe D - 1'),
  ('Heitor Dornelas Câmara Cocino da Costa', 'heitor.costa@aquila.com.br', 'Trainee 1'),
  ('Hélio Victor de Oliveira Gomes', 'helio.gomes@aquila.com.br', 'Classe D - 2'),
  ('Hemanuelle Teixeira Mota', 'hemanuelle.mota@aquila.com.br', 'Classe E - 2'),
  ('Henrique Camelo Schettino de Castilho', 'henrique.castilho@aquilaiberia.com.br', 'Trainee 3'),
  ('Henrique de Freitas Fernandes', 'henrique.freitas@aquila.com.br', 'Customer Success Pleno 1'),
  ('Henrique Gonçalves Ribeiro', 'henrique.ribeiro@aquila.com.br', 'Não se aplica'),
  ('Henrique José Pelegrini Pangoni', 'henrique.pangoni@aquila.com.br', 'Trainee 2'),
  ('Henrique Massa Guimarães', 'henrique.massa@aquila.com.br', 'Classe B - 2'),
  ('Henrique Menin de Carvalho', 'henrique.carvalho@aquila.com.br', 'Classe C - 1'),
  ('Henrique Vargas de Vasconcelos Cançado', 'henrique.vargas.fpj@aquila.com.br', 'Fornecedor'),
  ('Heron Leonardo Ricardo Morais de Barros', 'heron.barros@aquila.com.br', 'Classe C - 3'),
  ('Ícaro Sobrinho Lizardo', 'icaro.lizardo@aquila.com.br', 'Engenheiro de Dados Júnior 2'),
  ('Igor da Costa Siqueira', 'igor.siqueira@aquila.com.br', 'Classe D - 1'),
  ('Igor Dayrell Gomes', 'igor.dayrell@aquila.com.br', 'Classe E - 3'),
  ('Igor Monteiro Miranda', 'igor.miranda@aquila.com.br', 'Trainee 1'),
  ('Ingrid Danielle Rocha Martins', 'ingrid.martins@aquila.com.br', 'Júnior 1'),
  ('Isabela Brasil de Nazare', 'isabela.nazare@aquila.com.br', 'Classe D - 1'),
  ('Isabelle Couto Linhares Dufour', 'isabelle.couto.fpj@aquila.com.br', 'Fornecedor'),
  ('Isadora Rodrigues Caldas Andrade', 'isadora.andrade@aquila.com.br', 'Classe D - 1'),
  ('Iván Darío Vásquez Bernal', 'ivan.vasquez@aquilapacifico.com', 'Asociado 1'),
  ('Jakeline Juliana Soares de Lima', 'jakeline.soares@aquila.com.br', 'Classe E - 3'),
  ('Janaína Silva de Oliveira', 'janaina.oliveira@aquila.com.br', 'Júnior 1'),
  ('Jessyca Nayara Garcia de Carvalho', 'jessyca.carvalho@aquila.com.br', 'Não se aplica'),
  ('Jhonatas Tavares da Silva', 'jhonatas.silva.fpj@aquila.com.br', 'Fornecedor'),
  ('Joandesson Rocha Santos', 'joandesson.santos@aquila.com.br', 'Desenvolvedor Júnior 1'),
  ('João Batista Pires Júnior', 'joao.pires@aquila.com.br', 'Não se aplica'),
  ('João Felipe Passos Ferreira', 'joao.felipe@aquila.com.br', 'Classe B - 1'),
  ('Joel Cedraz de Oliveira Júnior', 'joel.cedraz@aquila.com.br', 'Não se aplica'),
  ('Jonas De Lima Da Silva', 'jonas.silva@aquila.com.br', 'Júnior 1'),
  ('Jonathan de Carvalho Domingos', 'jonathan.domingos@aquila.com.br', 'Não se aplica'),
  ('Jorge Luiz Orvalho', 'jorge.orvalho@aquila.com.br', 'Classe D - 1'),
  ('José Daniel Rincón Jiménez', 'daniel.rincon@aquilapacifico.com', 'Asociado 1'),
  ('José Eduardo Caicedo Durán', 'jose.caicedo@aquilapacifico.com', 'Sênior 1'),
  ('José Ítalo Rafael Pessoa de Figueirêdo', 'jose.figueiredo@aquila.com.br', 'Trainee 2'),
  ('José Olímpio Silva Coelho', 'jose.coelho@aquila.com.br', 'Trainee 1'),
  ('Juan Felipe Oliveros Zuleta', 'juanfelipe.oliveros@aquilapacifico.com', 'Júnior 2'),
  ('Juan Lucca de Siqueira Reis', 'juan.siqueira@aquila.com.br', 'Classe E - 3'),
  ('Júlia Macieira Lawton', 'julia.lawton@aquila.com.br', 'Classe C - 2'),
  ('Kaiky Adriano Vieira da Silva', 'kaiky.silva@aquila.com.br', 'Estagiário'),
  ('Kaio Vitor Soares da Silva Lima', 'kaio.lima@aquila.com.br', 'Júnior 1'),
  ('Kaique Sales Basto Bruno', 'kaique.basto.fpj@aquila.com.br', 'Fornecedor'),
  ('Karen Yumi Ossugui Kihara', 'karen.yumi@aquila.com.br', 'Classe D - 2'),
  ('Kaylane Jory de Souza', 'kaylane.jory@aquila.com.br', 'Estagiário'),
  ('Kleber Sathler Avelar', 'kleber.avelar@aquila.com.br', 'Não se aplica'),
  ('Kleiber de Souto Nogueira', 'kleiber.nogueira.fpj@aquila.com.br', 'Fornecedor'),
  ('Laira Aldenucci', 'laira.aldenucci@aquila.com.br', 'Classe D - 1'),
  ('Larissa Mayara de Queiroz Gonçalves de Oliveira', 'larissa.queiroz@aquila.com.br', 'Júnior 2'),
  ('Laura Barreto de Oliveira', 'laura.barreto@aquila.com.br', 'Classe C - 3'),
  ('Laura Isabel Tascón Yusty', 'laura.tascon@aquilapacifico.com', 'Júnior 1'),
  ('Laura Ponte de Freitas Campos', 'laura.campos@aquila.com.br', 'Júnior 1'),
  ('Leonardo Aguiar Lima', 'leonardo.lima@aquila.com.br', 'Classe D - 2'),
  ('Leonardo Botrel Tobias', 'leonardo.botrel@aquila.com.br', 'Desenvolvedor Pleno 1'),
  ('Leonardo Dornelles dos Santos', 'leonardo.santos@aquila.com.br', 'Classe C - 1'),
  ('Leonardo Mateus dos Santos', 'leonardo.mateus@aquila.com.br', 'Classe D - 3'),
  ('Leonardo Pimentel Fernandes de Melo', 'leonardo.melo@aquila.com.br', 'Estagiário'),
  ('Leonardo Rischele Felisbino', 'leonardo.rischele@aquila.com.br', 'Classe B - 3'),
  ('Leonardo Rocha Hamberger Morett', 'leonardo.morett@aquila.com.br', 'Estagiário'),
  ('Leticia Ferreira Brugger', 'leticia.ferreira@aquila.com.br', 'Classe D - 1'),
  ('Liège de Assis Pinto', 'liege.assis@aquila.com.br', 'Classe E - 3'),
  ('Lina Marcela Ruiz Cortés', 'lina.ruiz@aquilapacifico.com', 'Júnior 1'),
  ('Luan Sampaio Moreira da Silva', 'luan.sampaio.fpj@aquila.com.br', 'Fornecedor'),
  ('Luana Mazin Tsubone', 'luana.tsubone@aquila.com.br', 'Trainee 1'),
  ('Luana Vital Ferreira', 'luana.ferreira@aquila.com.br', 'Classe D - 2'),
  ('Lucas Bellini Azevedo', 'lucas.azevedo.fpj@aquila.com.br', 'Fornecedor'),
  ('Lucas Cardoso Marques dos Santos', 'lucas.santos@aquila.com.br', 'Classe E - 3'),
  ('Lucas Dias Padovan', 'lucas.padovan@aquila.com.br', 'Não se aplica'),
  ('Lucas Emilio de Oliveira Fernandes', 'lucas.fernandes@aquila.com.br', 'Classe E - 2'),
  ('Lucas Matheus Rodrigues dos Santos', 'lucas.rodrigues@aquila.com.br', 'Cientista de Dados Pleno 4'),
  ('Lucas Medeiros de Araújo Cunha', 'lucas.cunha@aquila.com.br', 'Estagiário'),
  ('Lucas Paschoal Teles de Andrade', 'lucas.andrade@aquila.com.br', 'Trainee 2'),
  ('Lucas Resende Ferreira', 'lucas.ferreira@aquila.com.br', 'Classe C - 2'),
  ('Lucas Ulhoa Gomes', 'lucas.gomes@aquila.com.br', 'Classe E - 3'),
  ('Lucas Valadares Madeira', 'lucas.valadares@aquila.com.br', 'Não se aplica'),
  ('Lucas Vieira Lara', 'lucas.lara@aquila.com.br', 'Classe C - 3'),
  ('Lucca Stochiero Vaz de Melo Caetano', 'lucca.caetano@aquila.com.br', 'Cientista de Dados Júnior 2'),
  ('Lucca Tourino Elian', 'lucca.tourino@aquila.com.br', 'Classe D - 2'),
  ('Lúcio Dos Anjos Silva Júnior', 'lucio.junior@aquila.com.br', 'Auxiliar em Gestão'),
  ('Luiz Eduardo de Oliveira Santos', 'luiz.santos@aquila.com.br', 'Não se aplica'),
  ('Luiz Henrique Bahia Lucciola', 'luiz.lucciola@aquila.com.br', 'Classe B - 1'),
  ('Luiz Henrique Zanforlin Pereira', 'luiz.zanforlin@aquila.com.br', 'Classe C - 3'),
  ('Luiz Paulo Dias', 'luiz.dias@aquila.com.br', 'Classe E - 3'),
  ('Luiz Rafael De Souza', 'luiz.souza@aquila.com.br', 'Engenheiro de Dados Júnior 2'),
  ('Luiza do Carmo Matheus', 'luiza.matheus@aquila.com.br', 'Pleno 2'),
  ('Marcel Jabbur Goulart', 'marcel.goulart@aquila.com.br', 'Classe C - 3'),
  ('Marcelo Fialho Petrulis', 'marcelo.petrulis@aquila.com.br', 'Classe E - 3'),
  ('Marcelo Rabelo Thebit Dolabela', 'marcelo.dolabela@aquila.com.br', 'Classe C - 2'),
  ('Marcio Luiz de Castro Filho', 'marcio.castro@aquila.com.br', 'Classe D - 2'),
  ('Márcio Matheus Monteiro Souto', 'marcio.monteiro@aquila.com.br', 'Classe E - 3'),
  ('Marco Antônio Maia Costa', 'marco.costa@aquila.com.br', 'Classe B - 2'),
  ('Marcos Tadeu Pinheiro Damasceno Portela', 'marcos.portela.fpj@aquila.com.br', 'Fornecedor'),
  ('Maria Aparecida do Carmo Rosa e Silva', 'maria.aparecida@aquila.com.br', 'Não se aplica'),
  ('Maria Cecília Santos Suarez', 'maria.suarez@aquila.com.br', 'Classe D - 1'),
  ('Maria Clara Costa Cristino', 'maria.cristino@aquila.com.br', 'Não se aplica'),
  ('Maria Clara de Amorim Gomes', 'maria.gomes@aquila.com.br', 'Estagiário'),
  ('Maria Eduarda de Arruda Teles', 'mariaeduarda.teles@aquila.com.br', 'Trainee 1'),
  ('Maria Eduarda Oliveira Moraes', 'maria.moraes@aquila.com.br', 'Estagiário'),
  ('Maria Fernanda Alves Bellini de Castro', 'maria.castro@aquila.com.br', 'Classe E - 3'),
  ('Maria Fernanda Rocha Gontijo', 'maria.gontijo@aquila.com.br', 'Classe C - 2'),
  ('Maria Valquíria Araújo de Moraes', 'valquiria.moraes.fpj@aquila.com.br', 'Fornecedor'),
  ('Mariana Alkmim de Miranda Guarda', 'mariana.guarda@aquila.com.br', 'Classe C - 1'),
  ('Mariana Fusco Pereira Amorim', 'mariana.fusco@aquila.com.br', 'Não se aplica'),
  ('Marina Almeida Lelis de Moura', 'marina.moura@aquila.com.br', 'Trainee 1'),
  ('Marina Ferreira Rodrigues', 'marina.rodrigues@aquila.com.br', 'Não se aplica'),
  ('Marina Kleinhappel Andrade', 'marina.andrade@aquila.com.br', 'Pleno 2'),
  ('Marina Muniz Pegler', 'marina.pegler@aquila.com.br', 'Classe C - 3'),
  ('Mário Bricio Magalhães Barbosa', 'mario.barbosa@aquila.com.br', 'Estagiário'),
  ('Mário Henrique França Marques', 'mario.marques@aquila.com.br', 'Classe B - 1'),
  ('Mário Rubens Negreiros Lopes', 'mario.negreiros@aquila.com.br', 'Classe C - 2'),
  ('Matheus Cavalcanti Lins de Oliveira', 'matheus.cavalcanti@aquila.com.br', 'Classe D - 2'),
  ('Matheus Eloir Abegg', 'matheus.abegg.fpj@aquila.com.br', 'Fornecedor'),
  ('Matheus Fernandes Pecegueiro', 'matheus.pecegueiro@aquila.com.br', 'Trainee 2'),
  ('Matheus Resende Faria', 'matheus.faria@aquila.com.br', 'Classe C - 1'),
  ('Melissa Reis de Oliveira Bortoncello', 'melissa.oliveira@aquila.com.br', 'Classe B - 3'),
  ('Miguel Seidel Ferreira Coelho', 'miguel.coelho@aquila.com.br', 'Classe E - 2'),
  ('Miguel Vitor Neves de Mattos', 'miguel.mattos@aquila.com.br', 'Trainee 1'),
  ('Milena Souza Paula', 'milena.souza@aquila.com.br', 'Classe E - 3'),
  ('Mirza Quintão Utsch', 'mirza.quintao@aquila.com.br', 'Classe B - 2'),
  ('Monara de Medeiros Linhares Fernandes', 'monara.linhares@aquila.com.br', 'Auxiliar Administrativo'),
  ('Murilo Henrique Maioli Pessoa Pereira', 'murilo.maioli@aquila.com.br', 'Classe D - 3'),
  ('Musa Varela de Almeida Rosas', 'musa.rosas@aquila.com.br', 'Classe D - 1'),
  ('Naiara Madeira Souza', 'naiara.madeira@aquila.com.br', 'Classe C - 3'),
  ('Natália Martins de Morais Godoy Porto', 'natalia.godoy@aquila.com.br', 'Classe B - 2'),
  ('Natanael Ferreira do Nascimento', 'natanael.ferreira.fpj@aquila.com.br', 'Fornecedor'),
  ('Nathalia Nayara Pinheiro Rievers', 'nathalia.rievers.fpj@aquila.com.br', 'Fornecedor'),
  ('Nathiele Dantas de Souza Garcia', 'nathiele.dantas@aquila.com.br', 'Classe D - 1'),
  ('Nathielle Lourranne Vieira dos Santos Souza', 'nathielle.lourranne@aquila.com.br', 'Trainee 1'),
  ('Nayara de Andrade Barbosa', 'nayara.barbosa@aquila.com.br', 'Trainee 1'),
  ('Nayara Luiza Vieira de Souza', 'nayara.souza@aquila.com.br', 'Trainee 1'),
  ('Newton Alves da Rocha Júnior', 'newton.junior@aquila.com.br', 'Classe B - 3'),
  ('Omar Vidal Nohmi', 'omar.nohmi@aquila.com.br', 'Classe C - 1'),
  ('Orlando Euler de Castro', 'orlando.euler@aquila.com.br', 'Não se aplica'),
  ('Otávio Santos Andrade', 'otavio.andrade@aquila.com.br', 'Não se aplica'),
  ('Pablo Augusto Mendonça Valadares', 'pablo.valadares.fpj@aquila.com.br', 'Fornecedor'),
  ('Pablo Vinicius Ramos Lopes', 'pablo.lopes@aquila.com.br', 'Não se aplica'),
  ('Patrícia Fernandes Misk Fontan', 'patricia.misk@aquila.com.br', 'Não se aplica'),
  ('Patrícia Goroncy', 'patricia.goroncy@aquila.com.br', 'Classe D - 3'),
  ('Paula Barros Macedo', 'paula.macedo@aquila.com.br', 'Trainee 1'),
  ('Paulo Cesar Marques Ribeiro', 'paulo.ribeiro@aquila.com.br', 'Pleno 2'),
  ('Paulo Eduardo de Aguiar Coimbra', 'paulo.coimbra@aquila.com.br', 'Não se aplica'),
  ('Paulo Henrique Valente de Moura Carvalho', 'paulo.valente@aquila.com.br', 'Classe C - 3'),
  ('Paulo Henryque de Souza Rocha', 'paulo.rocha@aquila.com.br', 'Classe D - 3'),
  ('Pedro Augusto Pena Oliveira', 'pedro.oliveira@aquila.com.br', 'Não se aplica'),
  ('Pedro Botelho Viotti de Almeida', 'pedro.almeida@aquila.com.br', 'Classe D - 1'),
  ('Pedro Estevam Fernandes Oliveira Dias', 'pedro.dias@aquila.com.br', 'Classe D - 3'),
  ('Pedro Ferrarezi de Assis', 'pedro.assis@aquila.com.br', 'Estagiário'),
  ('Pedro Henrique do Carmo Pires', 'pedro.carmo@aquila.com.br', 'Trainee 2'),
  ('Pedro Henrique Eduvige Amaral', 'pedro.amaral@aquila.com.br', 'Classe D - 2'),
  ('Pedro Henrique Heggendorn Bessa', 'pedro.bessa@aquila.com.br', 'Júnior 2'),
  ('Pedro Henrique Leone Rocha', 'pedro.rocha@aquila.com.br', 'Engenheiro de Dados Júnior 3'),
  ('Pedro Henrique Menezes dos Reis', 'pedro.menezes@aquila.com.br', 'Classe C - 3'),
  ('Pedro Lenti Barbosa', 'pedro.barbosa@aquila.com.br', 'Estagiário'),
  ('Pedro Lucianeti Brambilla', 'pedro.brambilla@aquila.com.br', 'Trainee 2'),
  ('Pedro Nicolau de Lima Júnior', 'pedro.lima@aquila.com.br', 'Classe B - 1'),
  ('Rafael da Costa Poleze', 'rafael.poleze@aquila.com.br', 'Classe D - 2'),
  ('Rafael Diniz Pessoa', 'rafael.diniz@aquila.com.br', 'Engenheiro de Dados Pleno 1'),
  ('Rafael Martins Godoy Rocha', 'rafael.godoy@aquila.com.br', 'Classe C - 3'),
  ('Rafael Monteiro Botelho', 'rafael.botelho@aquila.com.br', 'Classe D - 2'),
  ('Rafael Pinheiro Percínio Silva', 'rafael.pinheiro@aquila.com.br', 'Classe C - 3'),
  ('Rafael Silveira Ferreira Pacheco', 'rafael.pacheco@aquila.com.br', 'Classe C - 2'),
  ('Rafael Soares Caldeira Leitão Condé', 'rafael.conde@aquila.com.br', 'Classe D - 1'),
  ('Rafael Villar Merces', 'rafael.villar@aquila.com.br', 'Classe C - 2'),
  ('Rafaela Bittencourt França', 'rafaela.franca@aquila.com.br', 'Classe E - 3'),
  ('Raimundo Godoy Castro Filho', 'raimundo.godoy@aquila.com.br', 'Não se aplica'),
  ('Raissa Milagres de Paula', 'raissa.depaula@aquila.com.br', 'Trainee 2'),
  ('Ramon Ribeiro Feliciano', 'ramon.feliciano@aquila.com.br', 'Classe E - 3'),
  ('Ramontiher Dutra Madeira do Amaral', 'ramontiher.dutra@aquila.com.br', 'Não se aplica'),
  ('Raphael Augusto Silva Barone', 'raphael.barone@aquila.com.br', 'Classe C - 3'),
  ('Raphael Victor Ribeiro da Cruz', 'raphael.cruz@aquila.com.br', 'Não se aplica'),
  ('Raul Salazar Rodrigues Maciel', 'raul.maciel@aquila.com.br', 'Júnior 1'),
  ('Ray Queiroga Pinto Júnior', 'ray.junior@aquila.com.br', 'Classe B - 3'),
  ('Rebeca Pimenta Pataca', 'rebeca.pimenta@aquila.com.br', 'Classe E - 3'),
  ('Rejane Patrícia Guimarães Zerlottini', 'rejane.guimaraes@aquila.com.br', 'Não se aplica'),
  ('Renan Antonio Zampaolo', 'renan.zampaolo@aquila.com.br', 'Classe C - 3'),
  ('Renata Cristina de Melo Oliveira', 'renata.oliveira@aquila.com.br', 'Classe C - 2'),
  ('Renata Toneli Mendes', 'renata.toneli@aquila.com.br', 'Classe C - 2'),
  ('Renato Copello Lamarca', 'renato.lamarca@aquila.com.br', 'Classe B - 2'),
  ('Renato Fernandes Borges', 'renato.borges@aquila.com.br', 'Trainee 1'),
  ('Renato Pantel Pereira', 'renato.pantel@aquila.com.br', 'Classe B - 1'),
  ('Ricardo Marcel Santana Costa', 'ricardo.marcel@aquila.com.br', 'Classe C - 1'),
  ('Rita de Andrade', 'rita.andrade@aquila.com.br', 'Classe C - 2'),
  ('Rita De Cassia Pereira Soares', 'rita.pereira@aquila.com.br', 'Não se aplica'),
  ('Roberto Heleno de Oliveira Junior', 'roberto.heleno@aquila.com.br', 'Classe B - 2'),
  ('Robson de Lima Bernardes Júnior', 'robson.bernardes@aquila.com.br', 'Júnior 1'),
  ('Rodrigo Alkmim de Miranda Guarda', 'rodrigo.guarda@aquila.com.br', 'Estagiário'),
  ('Rodrigo Machado Bastos', 'rodrigo.bastos@aquila.com.br', 'Classe C - 3'),
  ('Rodrigo Portugal de Oliveira', 'rodrigo.portugal@aquila.com.br', 'Fornecedor'),
  ('Rodrigo Zacharias Neves', 'rodrigo.neves@aquila.com.br', 'Classe B - 3'),
  ('Rogério Silva Nacif', 'rogerio.nacif@aquila.com.br', 'Classe B - 2'),
  ('Roseli da Silva Correa Matosinhos', 'roseli.matosinhos@aquila.com.br', 'Não se aplica'),
  ('Rosinéia de Lima Bernardes', 'rosa.bernardes@aquila.com.br', 'Não se aplica'),
  ('Sâmia Nicolly Amaral de Souza', 'samia.souza@aquila.com.br', 'Classe E - 2'),
  ('Samuel Duarte de Queiroz', 'samuel.queiroz@aquila.com.br', 'Trainee 2'),
  ('Samuel Geronimo do Vale Almeida', 'samuel.almeida@aquila.com.br', 'Classe D - 1'),
  ('Samuel Lamera Portes Carneiro', 'samuel.carneiro.fpj@aquila.com.br', 'Fornecedor'),
  ('Sarah Braga Avila', 'sarah.avila@aquila.com.br', 'Classe D - 3'),
  ('Sarah Ihasmin Gomes', 'sarah.gomes@aquila.com.br', 'Auxiliar em Gestão 2'),
  ('Sarah Marques de Oliveira', 'sarah.oliveira@aquila.com.br', 'Estagiário'),
  ('Saulo Queiroga Lopes', 'saulo.lopes@aquila.com.br', 'Classe D - 2'),
  ('Sebastian Martinez Ceballos', 'sebastian.martinez@aquilapacifico.com', 'Lider de Proyectos 1'),
  ('Sebastian Suarez Duque', 'sebastian.suarez@aquilapacifico.com', 'Júnior 1'),
  ('Sheila Cristina Farias Rosa', 'sheila.farias@aquila.com.br', 'Não se aplica'),
  ('Silvio Soares Paraguassu', 'silvio.paraguassu@aquila.com.br', 'Classe D - 2'),
  ('Sofia de Figueiredo Lima', 'sofia.lima@aquila.com.br', 'Cientista de Dados Júnior 3'),
  ('Suhêrda Martins Lamounier', 'suherda.lamounier@aquila.com.br', 'Classe D - 2'),
  ('Tadeu Ribeiro de Lima', 'tadeu.lima@aquila.com.br', 'Classe B - 1'),
  ('Taiana Tonini Zanatta', 'taiana.zanatta@aquila.com.br', 'Classe B - 1'),
  ('Tania Lúcia das Dores Moura', 'tania.moura@aquila.com.br', 'Não se aplica'),
  ('Tarsianna Moura Bezerra Lima', 'tarsianna.lima@aquila.com.br', 'Estagiário'),
  ('Telveny Pinto Nascimento', 'telveny.nascimento@aquila.com.br', 'Não se aplica'),
  ('Thainá de Lima Oliveira Santana', 'thaina.santana@aquila.com.br', 'Classe D - 2'),
  ('Thais Gorgonio Pereira', 'thais.pereira@aquila.com.br', 'Classe E - 2'),
  ('Thatyane Campos Fonseca', 'thatyane.fonseca@aquila.com.br', 'Classe D - 1'),
  ('Thiago de Almeida Brandão e Souza', 'thiago.brandao@aquila.com.br', 'Classe B - 2'),
  ('Tiago Garcéa Rameh do Amaral', 'tiago.amaral@aquila.com.br', 'Trainee 1'),
  ('Tiago Luiz Hilário', 'tiago.hilario.fpj@aquila.com.br', 'Fornecedor'),
  ('Tiago Xavier Resende Oliveira', 'tiago.oliveira@aquila.com.br', 'Classe E - 3'),
  ('Toheá Ranzeti Antunes', 'tohea.antunes@aquila.com.br', 'Auxiliar Técnico'),
  ('Ullisses Cosme Gontijo', 'ullisses.gontijo@aquila.com.br', 'Trainee 1'),
  ('Vanessa Maciel Nessy', 'vanessa.nessy@aquila.com.br', 'Trainee 1'),
  ('Vanidy Bamberg', 'vanidy.bamberg@aquila.com.br', 'Auxiliar em Gestão 2'),
  ('Victor Alexandre Mendes Barros', 'victor.barros@aquila.com.br', 'Classe D - 1'),
  ('Victor Gomes Minelli Figueira', 'victor.minelli@aquila.com.br', 'Classe C - 2'),
  ('Victor Rodrigues Lakitin', 'victor.lakitin@aquila.com.br', 'Classe E - 3'),
  ('Victoria dos Santos Zini Silva', 'victoria.silva@aquila.com.br', 'Trainee 1'),
  ('Vinícius de Oliveira Fonseca', 'vinicius.fonseca@aquila.com.br', 'Classe E - 1'),
  ('Vinicius dos Santos Soares', 'vinicius.soares.fpj@aquila.com.br', 'Fornecedor'),
  ('Vinicius Miranda Barros', 'vinicius.miranda@aquila.com.br', 'Classe C - 2'),
  ('Vinniccius Jesusmar Azevedo Costa', 'vinniccius.costa@aquila.com.br', 'Auxiliar em Gestão 2'),
  ('Vitor Chaia Silva Servulo', 'vitor.chaia@aquila.com.br', 'Classe D - 1'),
  ('Vitor Isaias Zaquetti Agapito', 'vitor.agapito@aquila.com.br', 'Estagiário'),
  ('Vitor Rocha Caeiro', 'vitor.rocha@aquila.com.br', 'Classe E - 2'),
  ('Vitória Zanini de Figueiredo', 'vitoria.zanini@aquila.com.br', 'Classe D - 1'),
  ('Wanêssa Ribeiro Milagres', 'wanessa.ribeiro@aquila.com.br', 'Não se aplica'),
  ('Wanessa Ribeiro Pereira', 'wanessa.pereira@aquila.com.br', 'Trainee 1'),
  ('Winicius Antonio Souza Silva', 'winicius.silva@aquila.com.br', 'Cientista de Dados Júnior 2'),
  ('Yuri Gustavo Neves Barbosa', 'yuri.barbosa@aquila.com.br', 'Classe C - 1')
on conflict (email) do update set nome = excluded.nome, categoria = excluded.categoria;
