// Catálogo de soluções da Aquila — usado para pré-preencher o campo
// "Solução" (antigo "Escopo") no cadastro/edição de demandas. Uma demanda
// pode combinar mais de uma solução.
export const SOLUCOES_DISPONIVEIS: string[] = [
  "5S",
  "8 Passos da Excelência (Projeto)",
  "Administração Executiva",
  "Automação de Processos - IGMA Tech",
  "Box da Demanda",
  "Business Plan - Planos de Negõcio",
  "Célula de Valor Agregado",
  "Centro de Serviço Compartilhado",
  "Ciclo do Crédito Tributário",
  "Ciclo do Credito Tributário - IGMATech",
  "Ciclo do Parlamentar Excelente",
  "Ciclo Virtuoso da Aprendizagem",
  "Coaching",
  "Comercial",
  "Compliance",
  "Contrato Guarda Chuva",
  "Curso sob demanda",
  "Data Aquila - Índice Sob Demanda",
  "Data Edge – Engenharia de Dados",
  "Diagnóstico de Maturidade de Gestão",
  "EAD - 8 Passos da Excelência",
  "EAD - Excelência Comercial",
  "EAD - Excelência no Varejo",
  "EAD - FInanças",
  "EAD - Formação de Gestores",
  "ESG - Ambiental, Social e Governança",
  "Estudo de Viabilidade",
  "Excelência Comercial",
  "Excelência Comercial Go To Market",
  "Excelência Operacional",
  "Gerenciamento de Projetos",
  "Gestão da Inovação",
  "Gestão da Rotina",
  "Gestão de Ativos (Manutenção)",
  "Gestão de Investimentos (CAPEX)",
  "Gestão de Pessoas",
  "Gestão de Pessoas (Plano de Cargos e Salários)",
  "Gestão de Processos",
  "Gestão de Processos por meio de Célula de Valor Agregado (CVA)",
  "Gestão de Riscos e Controles Internos e Auditoria",
  "Gestão do Capital Empregado",
  "Gestão Educacional",
  "Gestão Financeira",
  "Gestão Integrada",
  "Governança Corporativa",
  "GTM – Go to Market",
  "Inteligência Competitiva por meio do Alinhamento de Metas",
  "Lean Office",
  "LGPD - Lei Geral de Proteção aos Dados",
  "M&A - Fusoes e Aquisicoes",
  "Matricial Integrado",
  "Matricial Integrado (Gestão de Custos)",
  "Matricial Integrado (Gestão de Despesas)",
  "Matricial Integrado (Gestão de Receitas)",
  "Matricial Integrado (Gestão do Capital Empregado)",
  "Monitoria",
  "Outsourcing",
  "Palestra de Gestão",
  "Planejamento Estratégico",
  "Pricing",
  "Produto de Dados IGMATech",
  "Programa de Excelência na Gestão Pública",
  "Programa de Excelência no Varejo",
  "Programa de Redução de Custos e Despesas por Meio da Base Zero",
  "Programa em Excelência em Projetos",
  "Programa PME - Os 8 Passos da Excelência",
  "Projetos de Inteligência Artificial",
  "Reestruturação Organizacional",
  "Remuneração Variável",
  "S&OP - Planejamento de Vendas e Operações",
  "Safety Maturity Roadmap",
  "SGI - Sistema de Gestão Integrado",
  "Software - Dashboard",
  "Software - Mercvrivs",
  "Software - Portal de Gestão (Módulo Processos)",
  "Software - Portal IGMATech",
  "Software Selection",
  "Software sob Demanda - IGMA TECH",
  "SST - Saúde e Segurança noTrabalho",
  "Supply Chain - Cadeia de Suprimentos",
  "Times de Excelência",
  "Treinamento -  Extrema Pressão",
  "Treinamento -  Plataforma do Futuro",
  "Treinamento - Ambientação",
  "Treinamento - BSC - BALANCED SCORECARD",
  "Treinamento - Capacitação no método de Investigação e Prevenção de Acidentes",
  "Treinamento - Estatística Básica",
  "Treinamento - Excel como Ferramenta de Gestão",
  "Treinamento - Excelência Comercial Básico",
  "Treinamento - Excelência na Gestão Escolar",
  "Treinamento - Finanças para Executivos",
  "Treinamento - Fábricas Virtuais",
  "Treinamento - Gerencial Integrado",
  "Treinamento - Gerenciamento de Projetos",
  "Treinamento - Gestão da Educação",
  "Treinamento - Inteligência Artificial",
  "Treinamento - Inteligência Competitiva",
  "Treinamento - Liderança e Gestão de Pessoas",
  "Treinamento - Marketing e Vendas",
  "Treinamento - Método Avançado",
  "Treinamento - Negociação de Alto Nível",
  "Treinamento - OBZ",
  "Treinamento - Power BI",
  "Treinamento - Programa de Excelência na Gestão Pública",
  "Treinamento - Programa de Formação de Gestores - Faixa Amarela",
  "Treinamento - Programa de Formação de Gestores - Faixa Branca",
  "Treinamento - Programa de Formação de Gestores - Faixa Preta",
  "Treinamento - Programa de Formação de Gestores - Faixa Verde",
  "Treinamento - SIGA",
  "Treinamento - VBA",
  "Treinamento 8 Passos da Excelência",
  "Treinamento Acess",
  "Treinamento Excelência Comercial",
  "Treinamento Excelência no Varejo",
  "Valuation",
];
